import { client } from "$lib/server/databaseClient";
import { INSERT_CONSUMPTION } from "$lib/server/queries";
import type { Actions } from "./$types";
import { error, fail } from "@sveltejs/kit";
import { superValidate, message } from "sveltekit-superforms/server";
import { z } from "zod";

const inputSchema = z.object({
  price: z
    .number()
    .gt(0)
    .lt(100)
    .default("" as unknown as number),
  gallons: z
    .number()
    .gt(0)
    .lt(50)
    .default("" as unknown as number),
  miles: z
    .number()
    .gt(0)
    .lt(1000)
    .default("" as unknown as number),
  notes: z.string().nullable(),
});

export const load = async (event) => {
  type Message = { isSuccess: boolean };

  const form = await superValidate<typeof inputSchema, Message>(
    event,
    inputSchema
  );
  return { form };
};

export const actions: Actions = {
  create: async ({ request, fetch }) => {
    const form = await superValidate(request, inputSchema);

    if (!form.valid) return fail(400, { form });

    const { price, gallons, miles, notes } = form.data;
    const res = await client.execute({
      sql: INSERT_CONSUMPTION,
      args: {
        carId: 4,
        price,
        gallons,
        miles,
        notes,
      },
    });

    if (res.rowsAffected != 1) error(505, "Error creating record");

    return message(form, { isSuccess: true });
  },
};

export const config = {
  isr: {
    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 28880,

    // Random token that can be provided in the URL to bypass the cached version of the asset, by requesting the asset
    // with a __prerender_bypass=<token> cookie.
    //
    // Making a `GET` or `HEAD` request with `x-prerender-revalidate: <token>` will force the asset to be re-validated.

    // List of valid query parameters. Other parameters (such as utm tracking codes) will be ignored,
    // ensuring that they do not result in content being regenerated unnecessarily
  },
};
